### ISSUE TITLE
请问14700KF的CPU，ProcessorType应该设置成多少？

### ISSUE THREAD

**Issue by millsguo** [yutianhot/MSI-Z790-Edge-WIFI-DDR5---i7-14700KF---AMD-6750GRE---Hackintosh-EFI#2]
RT

**Comment by millsguo** [comment]
已解决，选择正确的机型就可以了，主要是仿冒CPU参数

**Comment by yutianhot** [comment]
这个怎么选的，我其实也不懂哈。。 分享下你的看看。 我的EFI  intel的无线网卡没驱动。 亮度和声音无法调节

**Comment by millsguo** [comment]
> 这个怎么选的，我其实也不懂哈。。 分享下你的看看。 我的EFI intel的无线网卡没驱动。 亮度和声音无法调节

我用的博通的无线+蓝牙网卡，免驱的～
有线网卡是板载Intel I225V，也是免驱
亮度，我是台式机，不需要调，声音是可以调的，等我会发个我的EFI出来，给你参考

**Comment by millsguo** [comment]
已发布：https://github.com/millsguo/MSI-PRO-Z790-A-MAX-WIFI-D5-14700KF-RX6650XT-EFI
